### ISSUE TITLE
example seems to be broken

### ISSUE THREAD

**Issue by mt-digital** [lisapalathingal/PRMS_Adaptor#3]
At first when I ran your example 

```
python dataConverter.py LC.param
```

I got this error:

```
File "dataConverter.py", line 75, in parameterValuesToAnArray
    passArraytoGdal(nameOfOutputFile, fileHandle, parameterNames, index, numberOfColumns, numberOfRows)
NameError: global name 'nameOfOutputFile' is not defined
```

I have fixed this with my latest push to master, but now am getting this error:

```
EPSG 4326
None
ERROR
(-114.323106, 0.0011242812499999328, 0, 39.028019, 0, -0.0009341224489795812)
Traceback (most recent call last):
  File "dataConverter.py", line 92, in <module>
    parameterValuesToAnArray()
  File "dataConverter.py", line 75, in parameterValuesToAnArray
    passArraytoGdal(nameOfOutputFile, fileHandle, parameterNames, index, numberOfColumns, numberOfRows)
  File "dataConverter.py", line 44, in passArraytoGdal
    gdalDriver.writeRaster(nameOfOutputFile, parameterNames[index], numberOfRows, numberOfColumns, xavg, yavg, xMin, yMax, epsgValue, driver = outputFormat)
  File "/Users/mturner/workspace/wcwave/PRMS_Adaptor/gdalDriver.py", line 46, in writeRaster
    ds.SetGeoTransform(geoTransform)
UnboundLocalError: local variable 'ds' referenced before assignment
```

Let me know if I can help at all debugging.

**Comment by mt-digital** [comment]
Just pulled your changes and I'm getting the same error.  What's going on here:

```
EPSG 4326
None
ERROR
(-114.323106, 0.0011242812499999328, 0, 39.028019, 0, -0.0009341224489795812)
```

Why is `driver` `None`? Am I missing the NetCDF driver? Looks like you need to include more info on what packages you have installed, how you installed them, and what platform you're on (Windows, OS X, Linux).

I'm guessing that the expected output is a NetCDF file. But what will that file be named and where will it be put? What gets printed to stdout when you run this? I added a line for the exception to be printed in [`param2NetCDF.py`](https://github.com/lisapalathingal/PRMS_Adaptor/commit/3d186e06cf2b32c8d278dabe10e4ff0c43b013ce#diff-8afd612ff69b3d41b26846bdd6477f8fL183) and sure enough, the full error when I run it is `'NoneType' object has no attribute 'Create'`. So somehow I'm missing the NetCDF driver for GDAL.

**Comment by lipalath-ms** [comment]
I’m using Linux platform to run the program. I installed gdal using the command: 

sudo apt-get install python-gdal

The output is a set of NetCDF files in a new directory. The names of files are same as the names of variables. Names of variables will be passed to the writeRaster function (first argument in the writeRaster function is nameOfOutputFile). 

When you run the file, the following is printed to stdout for each variable:

EPSG 4326
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
