### ISSUE TITLE
Lat and Longitude are incorrect in the generated Geotiffs

### ISSUE THREAD

**Issue by ChaseCarthen** [lisapalathingal/PRMS_Adaptor#4]
The best way to fix to this by swapping the Longitude and Latitude at this line: https://github.com/lisapalathingal/PRMS_Adaptor/blob/master/param2NetCDF.py#L191.

This will allow any generate tiffs to be placed in the correct spot if loaded into GDAL and can be verified with any type of reference data.

**Comment by lipalath-ms** [comment]
Hi Chase, I swapped the latitude and longitude variables and inserted tiff files in the VW. Please let me know if you can place them in the correct spot.

**Comment by lipalath-ms** [comment]
Hi Chase, were you able to test my code?
