### ISSUE TITLE
error running test.py

### ISSUE THREAD

**Issue by mt-digital** [lisapalathingal/PRMS_Adaptor#7]
I get the following error when I try to run test.py:

![screen shot 2016-01-11 at 11 51 00 am](https://cloud.githubusercontent.com/assets/2425472/12244682/b00a9322-b859-11e5-99d5-f0afe69f790e.png)

It would be great to have this working so it could eventually we worked into a functional unittest.

**Comment by lipalath-ms** [comment]
Matt,

It's because animation input file is not included in the prms input_files
folder. The file is too big that I'm not able to upload it into the github
input_files folder.

Thanks,
Lisa

**Comment by mt-digital** [comment]
Oh ok, thanks for the explanation!
