### ISSUE TITLE
generation of animation netCDF uses too much memory

### ISSUE THREAD

**Issue by mt-digital** [lisapalathingal/PRMS_Adaptor#8]
Please process the animation file in chunks to avoid issues with ~1G of memory for a conversion. 

Consult with @itsrifat for more info.

**Comment by itsrifat** [comment]
@lisapalathingal 
We discussed this issue before. Can you check if you can make this conversion function work in a virtual machine (or a docker container) with smaller memory (512MB perhaps) ?
